/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CreateMaquinariasNivelDto { 
    idMaquinaria?: number;
    idNivelMantenimiento: number;
    posicion: number;
    tipo: string;
    tipoEquipamiento?: string;
    fecha: Date;
    horas?: number;
    kilometros?: number;
    terminado: boolean;
    idHmKm?: number;
    fechaProximoMantenimiento?: string;
}