/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface DetailDto { 
    id?: number;
    centroCompra?: string;
    nombreCentro?: string;
    matriculacion?: string;
    tipoMaquina?: string;
    categoria1?: string;
    categoria2?: string;
    categoria3?: string;
    aseguradora?: string;
    categoriaSeguro?: string;
    tipoSeguro?: string;
    numPoliza?: string;
    inicioPoliza?: string;
    finPoliza?: string;
    costeAnio?: number;
    costePrecio?: number;
    costeCodMoneda?: string;
    impuestoAnio?: number;
    impuestoPrecio?: number;
    impuestoCodMoneda?: string;
    chasisMarca?: string;
    chasisModelo?: string;
    chasisToneladas?: number;
    chasisPrecio?: number;
    chasisPago?: string;
    chasisContrato?: string;
    chasisBanco?: string;
    chasisFecha?: string;
    chasisDuracion?: number;
    chasisCodMoneda?: string;
    equipoMarca?: string;
    equipoModelo?: string;
    equipoVolumen?: string;
    equipoPrecio?: number;
    equipoPago?: string;
    equipoContrato?: string;
    equipoBanco?: string;
    equipoFecha?: string;
    equipoDuracion?: number;
    equipoCodMoneda?: string;
    implemento1Nombre?: string;
    implemento1Marca?: string;
    implemento1Modelo?: string;
    implemento1Precio?: number;
    implemento1Pago?: string;
    implemento1Contrato?: string;
    implemento1Banco?: string;
    implemento1Fecha?: string;
    implemento1Duracion?: number;
    implemento1CodMoneda?: string;
    implemento2Nombre?: string;
    implemento2Marca?: string;
    implemento2Modelo?: string;
    implemento2Precio?: number;
    implemento2Contrato?: string;
    implemento2Banco?: string;
    implemento2Fecha?: string;
    implemento2Duracion?: number;
    implemento2Pago?: string;
    implemento2CodMoneda?: string;
    estado?: string;
}