/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface FamilyDto { 
    id?: number;
    nombre?: string;
    tacografo?: number;
    levelIdentificador?: string;
    levelIdentificador2?: string;
    levelIdentificador3?: string;
    familia?: string;
    flagTacografo?: boolean;
    flagGnc?: boolean;
    flagItv?: boolean;
}