/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface GruaViewDto { 
    id?: number;
    matricula?: string;
    centro?: string;
    claveGuid?: string;
    delegacion?: string;
    familia?: string;
    subfamilia?: string;
    fechaProxima?: Date;
    idCentro?: number;
    idGrupoCentro?: number;
    fecha?: Date;
    createdBy?: string;
    createdAt?: Date;
    changedBy?: string;
    changedAt?: Date;
}