/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GruasDoc } from './gruasDoc';
import { Maquinaria } from './maquinaria';

export interface Grua { 
    id?: number;
    idEmpresa?: number;
    idMaquinaria?: number;
    maquinaria?: Maquinaria;
    fecha?: string;
    createdBy?: string;
    createdAt?: Date;
    changedBy?: string;
    changedAt?: Date;
    gruasDoc?: GruasDoc;
}