/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { MaquinariaDto } from './maquinariaDto';
import { ReferenciaMaterialDto } from './referenciaMaterialDto';

export interface HmKmDto { 
    id?: number;
    idEmpresa?: number;
    horas?: number;
    kilometros?: number;
    tipo?: string;
    externa?: boolean;
    fecha?: Date;
    idReferencia?: number;
    referenciaMaterial?: ReferenciaMaterialDto;
    idMaquinaria?: number;
    maquinaria?: MaquinariaDto;
    createdBy?: string;
    createdAt?: Date;
    changedBy?: string;
    changedAt?: Date;
}