/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InstalacionesOperacionesLangDto } from './instalacionesOperacionesLangDto';

export interface InstalacionesOperacioneDto { 
    id?: number;
    idEmpresa?: number;
    idElemento?: number;
    fecha?: string;
    actuante?: string;
    frecuencia?: number;
    createdBy?: string;
    createdAt?: Date;
    changedBy?: string;
    changedAt?: Date;
    langs?: Array<InstalacionesOperacionesLangDto>;
}