/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface LiterDto { 
    id?: number;
    fecha?: string;
    hora?: string;
    depositId?: number;
    litros?: number;
    machineId?: number;
    mes?: number;
}