/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface MachineDto { 
    id?: number;
    matricula?: string;
    familyId?: number;
    centerId?: string;
    horometro?: number;
    kilometro?: number;
    itv?: string;
    tacografo?: string;
    mantenimiento?: string;
    posicion?: number;
    bastidor?: string;
    operativa?: number;
    docitv?: string;
    docpermiso?: string;
    docpoliza?: string;
    mantenimiento2?: string;
    posicion2?: number;
    mantenimiento3?: string;
    posicion3?: number;
    docTaco?: string;
    docTrans?: string;
    serviceId?: string;
    ultItv?: string;
    fechaGnc?: string;
}