/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface MaintenanceDto { 
    id?: number;
    machineId?: number;
    horometroIni?: number;
    horometroFin?: number;
    kilometroIni?: number;
    kilometroFin?: number;
    fecha?: string;
    tipo?: number;
    nivel?: number;
    levelIde?: string;
}