/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CentrosCosteDto } from './centrosCosteDto';
import { MaquinariaDto } from './maquinariaDto';

export interface MaquinariasHistoricoDto { 
    id?: number;
    fechaCambio?: string;
    tipoCambio?: string;
    idMaquinaria?: number;
    maquinaria?: MaquinariaDto;
    idMaquinariaAsociada?: number;
    idCentro?: number;
    centrosCoste?: CentrosCosteDto;
    createdBy?: string;
    createdAt?: Date;
    changedBy?: string;
    changedAt?: Date;
}