/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FamiliaDto } from './familiaDto';
import { SubFamiliaDto } from './subFamiliaDto';

export interface MaquinariaShortDto { 
    id?: number;
    nombreCentro?: string;
    nombreGrupoCentro?: string;
    codigoCentro?: string;
    idCentroCompra?: number;
    familia?: FamiliaDto;
    subFamilia?: SubFamiliaDto;
    matricula?: string;
    fechaMatriculacion?: string;
    bastidor?: string;
    codTipoCombustible?: string;
}