/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Marca } from './marca';
import { ReferenciaMaterial } from './referenciaMaterial';

export interface MarcaReferenciaMaterial { 
    id?: number;
    idMarca?: number;
    marca?: Marca;
    idReferencia?: number;
    referenciaMaterial?: ReferenciaMaterial;
    createdBy?: string;
    createdAt?: Date;
    changedBy?: string;
    changedAt?: Date;
}