/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HmKm } from './hmKm';
import { MarcaReferenciaMaterial } from './marcaReferenciaMaterial';
import { RegulacionesStock } from './regulacionesStock';
import { Stock } from './stock';
import { SubFamiliaReferenciaMaterial } from './subFamiliaReferenciaMaterial';

export interface ReferenciaMaterial { 
    id?: number;
    idEmpresa?: number;
    codigoCategoria?: string;
    referencia?: string;
    descripcion?: string;
    createdBy?: string;
    createdAt?: Date;
    changedBy?: string;
    changedAt?: Date;
    stocks?: Array<Stock>;
    marcasReferencias?: Array<MarcaReferenciaMaterial>;
    subFamiliasReferencias?: Array<SubFamiliaReferenciaMaterial>;
    regulacionesStock?: Array<RegulacionesStock>;
    hmKm?: HmKm;
}