/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ReparacionViewDto { 
    id?: number;
    centroReparador?: string;
    claveGuid?: string;
    maquinaria?: string;
    tipoActuacion?: string;
    tipoMantenimiento?: string;
    fecha?: Date;
    proveedor?: string;
    albaran?: string;
    coste?: number;
    divisa?: string;
    codEstado?: string;
    comentarios?: string;
    idProveedor?: number;
    idMaquinaria?: number;
    idCentro?: number;
}