/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CentrosCosteDto } from './centrosCosteDto';
import { MaquinariaShortDto } from './maquinariaShortDto';
import { ProveedorDto } from './proveedorDto';

export interface ReparacionDto { 
    id?: number;
    idEmpresa?: number;
    idCentro?: number;
    centro?: CentrosCosteDto;
    idMaquinaria?: number;
    maquinaria?: MaquinariaShortDto;
    idProveedor?: number;
    proveedor?: ProveedorDto;
    fecha?: string;
    codTipoReparacion?: string;
    codNivelReparacion?: string;
    codMoneda?: string;
    codEstado?: string;
    repuestos?: number;
    neumaticos?: number;
    externos?: number;
    revision?: number;
    frenos?: number;
    transfer?: number;
    embragues?: number;
    latiguillos?: number;
    pintura?: number;
    obra?: number;
    otros?: number;
    comentarios?: string;
    observaciones?: string;
    automatico?: boolean;
    createdBy?: string;
    createdAt?: Date;
    changedBy?: string;
    changedAt?: Date;
}