/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ByteReadOnlyMemory } from './byteReadOnlyMemory';
import { Reparacion } from './reparacion';

export interface ReparacionesDoc { 
    claveGuid?: string;
    idReparacion?: number;
    reparacion?: Reparacion;
    codEstado?: string;
    id?: number;
    extension?: string;
    documento?: ByteReadOnlyMemory;
    nombre?: string;
}