/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CentrosCosteDto } from './centrosCosteDto';
import { DepositoDto } from './depositoDto';

export interface RepostajeDto { 
    id?: number;
    idEmpresa?: number;
    idCentro?: number;
    centro?: CentrosCosteDto;
    idMaquinaria?: number;
    idDeposito?: number;
    deposito?: DepositoDto;
    fecha?: Date;
    cantidad?: number;
    codUnidad?: string;
    cuenta?: string;
    tarjeta?: string;
    bidon?: string;
    idBidon?: number;
    createdBy?: string;
    createdAt?: Date;
    changedBy?: string;
    changedAt?: Date;
}