/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface SeguroViewDto { 
    id?: number;
    centro?: string;
    maquinaria?: string;
    aseguradora?: string;
    codEstadoSeguro?: string;
    codTipoSeguro?: string;
    numPoliza?: string;
    fechaInicio?: Date;
    fechaFin?: Date;
    importe?: number;
    codMoneda?: string;
    comentario?: string;
    idCentro?: number;
}