/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ReferenciaMaterialDto } from './referenciaMaterialDto';
import { ShortSubFamiliaDto } from './shortSubFamiliaDto';

export interface SubFamiliaReferenciaMaterialDto { 
    id?: number;
    idSubFamilia?: number;
    subFamilia?: ShortSubFamiliaDto;
    idReferencia?: number;
    referenciaMaterial?: ReferenciaMaterialDto;
    createdBy?: string;
    createdAt?: Date;
    changedBy?: string;
    changedAt?: Date;
}