/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UpdateImplementoDto { 
    id?: number;
    idEmpresa: number;
    idMaquinaria: number;
    descripcion: string;
    marca?: string;
    modelo?: string;
    serie?: string;
    precio?: number;
    tasa?: number;
    codMoneda?: string;
    contrato?: string;
    codTipoPago?: string;
    banco?: string;
    fecha?: string;
    duracion: number;
    mesesAmortizacion?: number;
    fechaAmortizacion?: string;
    mesesFinanciero?: number;
    fechaFinanciero?: string;
    porcentajeFinanciero?: number;
    codMonedaTasa?: string;
    idImplementoAsociado?: number;
    numeroActivoSap?: string;
}