/**
 * Valoriza IoT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { CreateExternalServiceDto } from '../model/createExternalServiceDto';
import { ExternalServiceDto } from '../model/externalServiceDto';
import { ExternalServiceDtoPagedResultDto } from '../model/externalServiceDtoPagedResultDto';
import { IncorrectResultDto } from '../model/incorrectResultDto';
import { UpdateExternalServiceDto } from '../model/updateExternalServiceDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ExternalServicesService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param actualPage 
     * @param pageSize 
     * @param sort 
     * @param filters 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiFeaturesV1ExternalServicesGet(actualPage?: number, pageSize?: number, sort?: string, filters?: { [key: string]: string; }, observe?: 'body', reportProgress?: boolean): Observable<ExternalServiceDtoPagedResultDto>;
    public apiFeaturesV1ExternalServicesGet(actualPage?: number, pageSize?: number, sort?: string, filters?: { [key: string]: string; }, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ExternalServiceDtoPagedResultDto>>;
    public apiFeaturesV1ExternalServicesGet(actualPage?: number, pageSize?: number, sort?: string, filters?: { [key: string]: string; }, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ExternalServiceDtoPagedResultDto>>;
    public apiFeaturesV1ExternalServicesGet(actualPage?: number, pageSize?: number, sort?: string, filters?: { [key: string]: string; }, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {





        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (actualPage !== undefined && actualPage !== null) {
            queryParameters = queryParameters.set('ActualPage', <any>actualPage);
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters = queryParameters.set('PageSize', <any>pageSize);
        }
        if (sort !== undefined && sort !== null) {
            queryParameters = queryParameters.set('Sort', <any>sort);
        }
        if (filters !== undefined && filters !== null) {
            queryParameters = queryParameters.set('Filters', <any>filters);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ExternalServiceDtoPagedResultDto>('get',`${this.basePath}/api/features/v1/externalServices`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param serviceApiProviderId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiFeaturesV1ExternalServicesGetByServiceApiProviderGet(serviceApiProviderId?: number, observe?: 'body', reportProgress?: boolean): Observable<ExternalServiceDto>;
    public apiFeaturesV1ExternalServicesGetByServiceApiProviderGet(serviceApiProviderId?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ExternalServiceDto>>;
    public apiFeaturesV1ExternalServicesGetByServiceApiProviderGet(serviceApiProviderId?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ExternalServiceDto>>;
    public apiFeaturesV1ExternalServicesGetByServiceApiProviderGet(serviceApiProviderId?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (serviceApiProviderId !== undefined && serviceApiProviderId !== null) {
            queryParameters = queryParameters.set('serviceApiProviderId', <any>serviceApiProviderId);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ExternalServiceDto>('get',`${this.basePath}/api/features/v1/externalServices/GetByServiceApiProvider`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiFeaturesV1ExternalServicesIdDelete(id: number, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public apiFeaturesV1ExternalServicesIdDelete(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public apiFeaturesV1ExternalServicesIdDelete(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public apiFeaturesV1ExternalServicesIdDelete(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiFeaturesV1ExternalServicesIdDelete.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<number>('delete',`${this.basePath}/api/features/v1/externalServices/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiFeaturesV1ExternalServicesIdGet(id: number, observe?: 'body', reportProgress?: boolean): Observable<ExternalServiceDto>;
    public apiFeaturesV1ExternalServicesIdGet(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ExternalServiceDto>>;
    public apiFeaturesV1ExternalServicesIdGet(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ExternalServiceDto>>;
    public apiFeaturesV1ExternalServicesIdGet(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiFeaturesV1ExternalServicesIdGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ExternalServiceDto>('get',`${this.basePath}/api/features/v1/externalServices/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiFeaturesV1ExternalServicesPost(body?: CreateExternalServiceDto, observe?: 'body', reportProgress?: boolean): Observable<ExternalServiceDto>;
    public apiFeaturesV1ExternalServicesPost(body?: CreateExternalServiceDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ExternalServiceDto>>;
    public apiFeaturesV1ExternalServicesPost(body?: CreateExternalServiceDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ExternalServiceDto>>;
    public apiFeaturesV1ExternalServicesPost(body?: CreateExternalServiceDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<ExternalServiceDto>('post',`${this.basePath}/api/features/v1/externalServices`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiFeaturesV1ExternalServicesPut(body?: UpdateExternalServiceDto, observe?: 'body', reportProgress?: boolean): Observable<ExternalServiceDto>;
    public apiFeaturesV1ExternalServicesPut(body?: UpdateExternalServiceDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ExternalServiceDto>>;
    public apiFeaturesV1ExternalServicesPut(body?: UpdateExternalServiceDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ExternalServiceDto>>;
    public apiFeaturesV1ExternalServicesPut(body?: UpdateExternalServiceDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<ExternalServiceDto>('put',`${this.basePath}/api/features/v1/externalServices`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
