/**
 * Valoriza IoT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { CreateServiceApiProviderDto } from '../model/createServiceApiProviderDto';
import { IncorrectResultDto } from '../model/incorrectResultDto';
import { ServiceApiProviderDto } from '../model/serviceApiProviderDto';
import { ServiceApiProviderDtoPagedResultDto } from '../model/serviceApiProviderDtoPagedResultDto';
import { UpdateServiceApiProviderDto } from '../model/updateServiceApiProviderDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ServiceApiProvidersService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param actualPage 
     * @param pageSize 
     * @param sort 
     * @param filters 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiFeaturesV1ServiceApiProvidersGet(actualPage?: number, pageSize?: number, sort?: string, filters?: { [key: string]: string; }, observe?: 'body', reportProgress?: boolean): Observable<ServiceApiProviderDtoPagedResultDto>;
    public apiFeaturesV1ServiceApiProvidersGet(actualPage?: number, pageSize?: number, sort?: string, filters?: { [key: string]: string; }, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ServiceApiProviderDtoPagedResultDto>>;
    public apiFeaturesV1ServiceApiProvidersGet(actualPage?: number, pageSize?: number, sort?: string, filters?: { [key: string]: string; }, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ServiceApiProviderDtoPagedResultDto>>;
    public apiFeaturesV1ServiceApiProvidersGet(actualPage?: number, pageSize?: number, sort?: string, filters?: { [key: string]: string; }, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {





        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (actualPage !== undefined && actualPage !== null) {
            queryParameters = queryParameters.set('ActualPage', <any>actualPage);
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters = queryParameters.set('PageSize', <any>pageSize);
        }
        if (sort !== undefined && sort !== null) {
            queryParameters = queryParameters.set('Sort', <any>sort);
        }
        if (filters !== undefined && filters !== null) {
            queryParameters = queryParameters.set('Filters', <any>filters);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ServiceApiProviderDtoPagedResultDto>('get',`${this.basePath}/api/features/v1/serviceApiProviders`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiFeaturesV1ServiceApiProvidersIdDelete(id: number, observe?: 'body', reportProgress?: boolean): Observable<number>;
    public apiFeaturesV1ServiceApiProvidersIdDelete(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<number>>;
    public apiFeaturesV1ServiceApiProvidersIdDelete(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<number>>;
    public apiFeaturesV1ServiceApiProvidersIdDelete(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiFeaturesV1ServiceApiProvidersIdDelete.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<number>('delete',`${this.basePath}/api/features/v1/serviceApiProviders/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiFeaturesV1ServiceApiProvidersIdGet(id: number, observe?: 'body', reportProgress?: boolean): Observable<ServiceApiProviderDto>;
    public apiFeaturesV1ServiceApiProvidersIdGet(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ServiceApiProviderDto>>;
    public apiFeaturesV1ServiceApiProvidersIdGet(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ServiceApiProviderDto>>;
    public apiFeaturesV1ServiceApiProvidersIdGet(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiFeaturesV1ServiceApiProvidersIdGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ServiceApiProviderDto>('get',`${this.basePath}/api/features/v1/serviceApiProviders/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiFeaturesV1ServiceApiProvidersPost(body?: CreateServiceApiProviderDto, observe?: 'body', reportProgress?: boolean): Observable<ServiceApiProviderDto>;
    public apiFeaturesV1ServiceApiProvidersPost(body?: CreateServiceApiProviderDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ServiceApiProviderDto>>;
    public apiFeaturesV1ServiceApiProvidersPost(body?: CreateServiceApiProviderDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ServiceApiProviderDto>>;
    public apiFeaturesV1ServiceApiProvidersPost(body?: CreateServiceApiProviderDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<ServiceApiProviderDto>('post',`${this.basePath}/api/features/v1/serviceApiProviders`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiFeaturesV1ServiceApiProvidersPut(body?: UpdateServiceApiProviderDto, observe?: 'body', reportProgress?: boolean): Observable<ServiceApiProviderDto>;
    public apiFeaturesV1ServiceApiProvidersPut(body?: UpdateServiceApiProviderDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ServiceApiProviderDto>>;
    public apiFeaturesV1ServiceApiProvidersPut(body?: UpdateServiceApiProviderDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ServiceApiProviderDto>>;
    public apiFeaturesV1ServiceApiProvidersPut(body?: UpdateServiceApiProviderDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<ServiceApiProviderDto>('put',`${this.basePath}/api/features/v1/serviceApiProviders`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
