/**
 * Valoriza IoT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CreateDeviceDto { 
    name: string;
    deviceUniqueId: string;
    serviceApiProviderId: number;
    centerGroupId: number;
    centerId: number;
    centerGroup?: string;
    center?: string;
    originId: number;
    originType: string;
    ioTHub?: string;
    module?: string;
    state: string;
}