/**
 * Valoriza IoT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AzureFunctionDto } from './azureFunctionDto';
import { ServiceApiProviderDto } from './serviceApiProviderDto';

export interface ExternalServiceDto { 
    id?: number;
    url?: string;
    httpVerb?: number;
    authType?: string;
    username?: string;
    password?: string;
    oAuthUrl?: string;
    cronExpression?: string;
    availableDriverId?: number;
    availableDriverName?: string;
    invocationDefinitionId?: number;
    invocationDefinitionName?: string;
    httpServiceTypeId?: number;
    httpServiceTypeName?: string;
    document?: string;
    orgId?: number;
    stateId?: number;
    guid?: string;
    permission?: number;
    serviceApiProviderId?: number;
    azureFunctionId?: number;
    serviceApiProvider?: ServiceApiProviderDto;
    azureFunction?: AzureFunctionDto;
    createdBy?: string;
    createdAt?: Date;
    changedBy?: string;
    changedAt?: Date;
    deletedBy?: string;
    deletedAt?: Date;
}