/**
 * Valoriza IoT API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UpdateDeviceToBeProvisionedDto { 
    id: number;
    idExternalService: number;
    deviceName?: string;
    deviceCenterGroupId?: number;
    deviceCenterId?: number;
    deviceOriginId?: number;
    deviceOriginType?: string;
}