export * from './amortizaciones.service';
import { AmortizacionesService } from './amortizaciones.service';
export * from './appParameter.service';
import { AppParameterService } from './appParameter.service';
export * from './bidones.service';
import { BidonesService } from './bidones.service';
export * from './categorias.service';
import { CategoriasService } from './categorias.service';
export * from './centrosCostes.service';
import { CentrosCostesService } from './centrosCostes.service';
export * from './combustibles.service';
import { CombustiblesService } from './combustibles.service';
export * from './depositos.service';
import { DepositosService } from './depositos.service';
export * from './familias.service';
import { FamiliasService } from './familias.service';
export * from './gastosTaller.service';
import { GastosTallerService } from './gastosTaller.service';
export * from './globalTables.service';
import { GlobalTablesService } from './globalTables.service';
export * from './globalTablesValues.service';
import { GlobalTablesValuesService } from './globalTablesValues.service';
export * from './globalTablesValuesLang.service';
import { GlobalTablesValuesLangService } from './globalTablesValuesLang.service';
export * from './gnc.service';
import { GncService } from './gnc.service';
export * from './gncDocs.service';
import { GncDocsService } from './gncDocs.service';
export * from './gruas.service';
import { GruasService } from './gruas.service';
export * from './gruposCentro.service';
import { GruposCentroService } from './gruposCentro.service';
export * from './hmKm.service';
import { HmKmService } from './hmKm.service';
export * from './hmKmHistorico.service';
import { HmKmHistoricoService } from './hmKmHistorico.service';
export * from './impuestos.service';
import { ImpuestosService } from './impuestos.service';
export * from './impuestosHistorico.service';
import { ImpuestosHistoricoService } from './impuestosHistorico.service';
export * from './instalaciones.service';
import { InstalacionesService } from './instalaciones.service';
export * from './maquinariaCambioDeCentro.service';
import { MaquinariaCambioDeCentroService } from './maquinariaCambioDeCentro.service';
export * from './maquinarias.service';
import { MaquinariasService } from './maquinarias.service';
export * from './maquinariasChasis.service';
import { MaquinariasChasisService } from './maquinariasChasis.service';
export * from './maquinariasDocs.service';
import { MaquinariasDocsService } from './maquinariasDocs.service';
export * from './maquinariasEquipos.service';
import { MaquinariasEquiposService } from './maquinariasEquipos.service';
export * from './maquinariasHistorico.service';
import { MaquinariasHistoricoService } from './maquinariasHistorico.service';
export * from './maquinariasImagenesDocs.service';
import { MaquinariasImagenesDocsService } from './maquinariasImagenesDocs.service';
export * from './maquinariasImplementos.service';
import { MaquinariasImplementosService } from './maquinariasImplementos.service';
export * from './maquinariasInspeccionesTecnicas.service';
import { MaquinariasInspeccionesTecnicasService } from './maquinariasInspeccionesTecnicas.service';
export * from './maquinariasInspeccionesTecnicasDocs.service';
import { MaquinariasInspeccionesTecnicasDocsService } from './maquinariasInspeccionesTecnicasDocs.service';
export * from './maquinariasInspeccionesTecnicasHistorico.service';
import { MaquinariasInspeccionesTecnicasHistoricoService } from './maquinariasInspeccionesTecnicasHistorico.service';
export * from './maquinariasNiveles.service';
import { MaquinariasNivelesService } from './maquinariasNiveles.service';
export * from './maquinariasNivelesDocs.service';
import { MaquinariasNivelesDocsService } from './maquinariasNivelesDocs.service';
export * from './maquinariasObservaciones.service';
import { MaquinariasObservacionesService } from './maquinariasObservaciones.service';
export * from './maquinariasPartesDeTrabajoDocumentos.service';
import { MaquinariasPartesDeTrabajoDocumentosService } from './maquinariasPartesDeTrabajoDocumentos.service';
export * from './maquinariasReparaciones.service';
import { MaquinariasReparacionesService } from './maquinariasReparaciones.service';
export * from './maquinariasReparacionesDocs.service';
import { MaquinariasReparacionesDocsService } from './maquinariasReparacionesDocs.service';
export * from './maquinariasReparacionesHistorico.service';
import { MaquinariasReparacionesHistoricoService } from './maquinariasReparacionesHistorico.service';
export * from './maquinariasRepostajes.service';
import { MaquinariasRepostajesService } from './maquinariasRepostajes.service';
export * from './maquinariasTacografos.service';
import { MaquinariasTacografosService } from './maquinariasTacografos.service';
export * from './marcas.service';
import { MarcasService } from './marcas.service';
export * from './nivelMantenimientoAccion.service';
import { NivelMantenimientoAccionService } from './nivelMantenimientoAccion.service';
export * from './nivelMantenimientoAccionesLang.service';
import { NivelMantenimientoAccionesLangService } from './nivelMantenimientoAccionesLang.service';
export * from './nivelesDeMantenimiento.service';
import { NivelesDeMantenimientoService } from './nivelesDeMantenimiento.service';
export * from './nivelesDeMantenimientoTipo.service';
import { NivelesDeMantenimientoTipoService } from './nivelesDeMantenimientoTipo.service';
export * from './nivelesDeMantenimientoTipoDeAccin.service';
import { NivelesDeMantenimientoTipoDeAccinService } from './nivelesDeMantenimientoTipoDeAccin.service';
export * from './nivelesGrupoAccion.service';
import { NivelesGrupoAccionService } from './nivelesGrupoAccion.service';
export * from './partesDeTrabajo.service';
import { PartesDeTrabajoService } from './partesDeTrabajo.service';
export * from './partesDeTrabajoDocumentos.service';
import { PartesDeTrabajoDocumentosService } from './partesDeTrabajoDocumentos.service';
export * from './partesDeTrabajoMateriales.service';
import { PartesDeTrabajoMaterialesService } from './partesDeTrabajoMateriales.service';
export * from './partesDeTrabajoMecanicos.service';
import { PartesDeTrabajoMecanicosService } from './partesDeTrabajoMecanicos.service';
export * from './pesoYCarga.service';
import { PesoYCargaService } from './pesoYCarga.service';
export * from './prestamosYStock.service';
import { PrestamosYStockService } from './prestamosYStock.service';
export * from './proveedores.service';
import { ProveedoresService } from './proveedores.service';
export * from './referenciaDeMateriales.service';
import { ReferenciaDeMaterialesService } from './referenciaDeMateriales.service';
export * from './regulacionesDeStock.service';
import { RegulacionesDeStockService } from './regulacionesDeStock.service';
export * from './seguros.service';
import { SegurosService } from './seguros.service';
export * from './stock.service';
import { StockService } from './stock.service';
export * from './tacografosDoc.service';
import { TacografosDocService } from './tacografosDoc.service';
export * from './unidadesDeMedida.service';
import { UnidadesDeMedidaService } from './unidadesDeMedida.service';
export * from './unidadesDeMedidaTiposDeCombustible.service';
import { UnidadesDeMedidaTiposDeCombustibleService } from './unidadesDeMedidaTiposDeCombustible.service';
export * from './usuarioCentro.service';
import { UsuarioCentroService } from './usuarioCentro.service';
export * from './valorizaGlobalTable.service';
import { ValorizaGlobalTableService } from './valorizaGlobalTable.service';
export * from './vistas.service';
import { VistasService } from './vistas.service';
export const APIS = [AmortizacionesService, AppParameterService, BidonesService, CategoriasService, CentrosCostesService, CombustiblesService, DepositosService, FamiliasService, GastosTallerService, GlobalTablesService, GlobalTablesValuesService, GlobalTablesValuesLangService, GncService, GncDocsService, GruasService, GruposCentroService, HmKmService, HmKmHistoricoService, ImpuestosService, ImpuestosHistoricoService, InstalacionesService, MaquinariaCambioDeCentroService, MaquinariasService, MaquinariasChasisService, MaquinariasDocsService, MaquinariasEquiposService, MaquinariasHistoricoService, MaquinariasImagenesDocsService, MaquinariasImplementosService, MaquinariasInspeccionesTecnicasService, MaquinariasInspeccionesTecnicasDocsService, MaquinariasInspeccionesTecnicasHistoricoService, MaquinariasNivelesService, MaquinariasNivelesDocsService, MaquinariasObservacionesService, MaquinariasPartesDeTrabajoDocumentosService, MaquinariasReparacionesService, MaquinariasReparacionesDocsService, MaquinariasReparacionesHistoricoService, MaquinariasRepostajesService, MaquinariasTacografosService, MarcasService, NivelMantenimientoAccionService, NivelMantenimientoAccionesLangService, NivelesDeMantenimientoService, NivelesDeMantenimientoTipoService, NivelesDeMantenimientoTipoDeAccinService, NivelesGrupoAccionService, PartesDeTrabajoService, PartesDeTrabajoDocumentosService, PartesDeTrabajoMaterialesService, PartesDeTrabajoMecanicosService, PesoYCargaService, PrestamosYStockService, ProveedoresService, ReferenciaDeMaterialesService, RegulacionesDeStockService, SegurosService, StockService, TacografosDocService, UnidadesDeMedidaService, UnidadesDeMedidaTiposDeCombustibleService, UsuarioCentroService, ValorizaGlobalTableService, VistasService];
