/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { CreateMarcaReferenciaMaterialDto } from '../model/createMarcaReferenciaMaterialDto';
import { CreateReferenciaMaterialDto } from '../model/createReferenciaMaterialDto';
import { CreateSubFamiliaReferenciaMaterialDto } from '../model/createSubFamiliaReferenciaMaterialDto';
import { MarcaReferenciaMaterialDto } from '../model/marcaReferenciaMaterialDto';
import { MarcaReferenciaMaterialDtoPaginatedResult } from '../model/marcaReferenciaMaterialDtoPaginatedResult';
import { ProblemDetails } from '../model/problemDetails';
import { ReferenciaMaterialDto } from '../model/referenciaMaterialDto';
import { ReferenciaMaterialDtoPaginatedResult } from '../model/referenciaMaterialDtoPaginatedResult';
import { SubFamiliaReferenciaMaterialDto } from '../model/subFamiliaReferenciaMaterialDto';
import { SubFamiliaReferenciaMaterialDtoPaginatedResult } from '../model/subFamiliaReferenciaMaterialDtoPaginatedResult';
import { UpdateMarcaReferenciaMaterialDto } from '../model/updateMarcaReferenciaMaterialDto';
import { UpdateReferenciaMaterialDto } from '../model/updateReferenciaMaterialDto';
import { UpdateSubFamiliaReferenciaMaterialDto } from '../model/updateSubFamiliaReferenciaMaterialDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ReferenciaDeMaterialesService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param Q 
     * @param sort 
     * @param page 
     * @param pageSize 
     * @param filters 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV2ReferenciaMaterialesGet(Q?: string, sort?: string, page?: number, pageSize?: number, filters?: { [key: string]: string; }, observe?: 'body', reportProgress?: boolean): Observable<ReferenciaMaterialDtoPaginatedResult>;
    public apiV2ReferenciaMaterialesGet(Q?: string, sort?: string, page?: number, pageSize?: number, filters?: { [key: string]: string; }, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ReferenciaMaterialDtoPaginatedResult>>;
    public apiV2ReferenciaMaterialesGet(Q?: string, sort?: string, page?: number, pageSize?: number, filters?: { [key: string]: string; }, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ReferenciaMaterialDtoPaginatedResult>>;
    public apiV2ReferenciaMaterialesGet(Q?: string, sort?: string, page?: number, pageSize?: number, filters?: { [key: string]: string; }, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {






        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (Q !== undefined && Q !== null) {
            queryParameters = queryParameters.set('Q', <any>Q);
        }
        if (sort !== undefined && sort !== null) {
            queryParameters = queryParameters.set('Sort', <any>sort);
        }
        if (page !== undefined && page !== null) {
            queryParameters = queryParameters.set('Page', <any>page);
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters = queryParameters.set('PageSize', <any>pageSize);
        }
        if (filters !== undefined && filters !== null) {
            Object.keys(filters).forEach((key) => {queryParameters = queryParameters.set(key, filters[key]);});
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ReferenciaMaterialDtoPaginatedResult>('get',`${this.basePath}/api/v2/referenciaMateriales`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV2ReferenciaMaterialesIdDelete(id: number, observe?: 'body', reportProgress?: boolean): Observable<ReferenciaMaterialDto>;
    public apiV2ReferenciaMaterialesIdDelete(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ReferenciaMaterialDto>>;
    public apiV2ReferenciaMaterialesIdDelete(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ReferenciaMaterialDto>>;
    public apiV2ReferenciaMaterialesIdDelete(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiV2ReferenciaMaterialesIdDelete.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ReferenciaMaterialDto>('delete',`${this.basePath}/api/v2/referenciaMateriales/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV2ReferenciaMaterialesIdGet(id: number, observe?: 'body', reportProgress?: boolean): Observable<ReferenciaMaterialDto>;
    public apiV2ReferenciaMaterialesIdGet(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ReferenciaMaterialDto>>;
    public apiV2ReferenciaMaterialesIdGet(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ReferenciaMaterialDto>>;
    public apiV2ReferenciaMaterialesIdGet(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiV2ReferenciaMaterialesIdGet.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ReferenciaMaterialDto>('get',`${this.basePath}/api/v2/referenciaMateriales/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param Q 
     * @param sort 
     * @param page 
     * @param pageSize 
     * @param filters 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV2ReferenciaMaterialesMarcaGet(Q?: string, sort?: string, page?: number, pageSize?: number, filters?: { [key: string]: string; }, observe?: 'body', reportProgress?: boolean): Observable<MarcaReferenciaMaterialDtoPaginatedResult>;
    public apiV2ReferenciaMaterialesMarcaGet(Q?: string, sort?: string, page?: number, pageSize?: number, filters?: { [key: string]: string; }, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MarcaReferenciaMaterialDtoPaginatedResult>>;
    public apiV2ReferenciaMaterialesMarcaGet(Q?: string, sort?: string, page?: number, pageSize?: number, filters?: { [key: string]: string; }, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MarcaReferenciaMaterialDtoPaginatedResult>>;
    public apiV2ReferenciaMaterialesMarcaGet(Q?: string, sort?: string, page?: number, pageSize?: number, filters?: { [key: string]: string; }, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {






        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (Q !== undefined && Q !== null) {
            queryParameters = queryParameters.set('Q', <any>Q);
        }
        if (sort !== undefined && sort !== null) {
            queryParameters = queryParameters.set('Sort', <any>sort);
        }
        if (page !== undefined && page !== null) {
            queryParameters = queryParameters.set('Page', <any>page);
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters = queryParameters.set('PageSize', <any>pageSize);
        }
        if (filters !== undefined && filters !== null) {
            Object.keys(filters).forEach((key) => {queryParameters = queryParameters.set(key, filters[key]);});
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<MarcaReferenciaMaterialDtoPaginatedResult>('get',`${this.basePath}/api/v2/referenciaMateriales/marca`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV2ReferenciaMaterialesMarcaIdDelete(id: number, observe?: 'body', reportProgress?: boolean): Observable<MarcaReferenciaMaterialDto>;
    public apiV2ReferenciaMaterialesMarcaIdDelete(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MarcaReferenciaMaterialDto>>;
    public apiV2ReferenciaMaterialesMarcaIdDelete(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MarcaReferenciaMaterialDto>>;
    public apiV2ReferenciaMaterialesMarcaIdDelete(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiV2ReferenciaMaterialesMarcaIdDelete.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<MarcaReferenciaMaterialDto>('delete',`${this.basePath}/api/v2/referenciaMateriales/marca/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV2ReferenciaMaterialesMarcaIdGet(id: number, observe?: 'body', reportProgress?: boolean): Observable<MarcaReferenciaMaterialDto>;
    public apiV2ReferenciaMaterialesMarcaIdGet(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MarcaReferenciaMaterialDto>>;
    public apiV2ReferenciaMaterialesMarcaIdGet(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MarcaReferenciaMaterialDto>>;
    public apiV2ReferenciaMaterialesMarcaIdGet(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiV2ReferenciaMaterialesMarcaIdGet.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<MarcaReferenciaMaterialDto>('get',`${this.basePath}/api/v2/referenciaMateriales/marca/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV2ReferenciaMaterialesMarcaPost(body?: CreateMarcaReferenciaMaterialDto, observe?: 'body', reportProgress?: boolean): Observable<MarcaReferenciaMaterialDto>;
    public apiV2ReferenciaMaterialesMarcaPost(body?: CreateMarcaReferenciaMaterialDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MarcaReferenciaMaterialDto>>;
    public apiV2ReferenciaMaterialesMarcaPost(body?: CreateMarcaReferenciaMaterialDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MarcaReferenciaMaterialDto>>;
    public apiV2ReferenciaMaterialesMarcaPost(body?: CreateMarcaReferenciaMaterialDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<MarcaReferenciaMaterialDto>('post',`${this.basePath}/api/v2/referenciaMateriales/marca`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV2ReferenciaMaterialesMarcaPut(body?: UpdateMarcaReferenciaMaterialDto, observe?: 'body', reportProgress?: boolean): Observable<MarcaReferenciaMaterialDto>;
    public apiV2ReferenciaMaterialesMarcaPut(body?: UpdateMarcaReferenciaMaterialDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<MarcaReferenciaMaterialDto>>;
    public apiV2ReferenciaMaterialesMarcaPut(body?: UpdateMarcaReferenciaMaterialDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<MarcaReferenciaMaterialDto>>;
    public apiV2ReferenciaMaterialesMarcaPut(body?: UpdateMarcaReferenciaMaterialDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<MarcaReferenciaMaterialDto>('put',`${this.basePath}/api/v2/referenciaMateriales/marca`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV2ReferenciaMaterialesPost(body?: CreateReferenciaMaterialDto, observe?: 'body', reportProgress?: boolean): Observable<ReferenciaMaterialDto>;
    public apiV2ReferenciaMaterialesPost(body?: CreateReferenciaMaterialDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ReferenciaMaterialDto>>;
    public apiV2ReferenciaMaterialesPost(body?: CreateReferenciaMaterialDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ReferenciaMaterialDto>>;
    public apiV2ReferenciaMaterialesPost(body?: CreateReferenciaMaterialDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<ReferenciaMaterialDto>('post',`${this.basePath}/api/v2/referenciaMateriales`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV2ReferenciaMaterialesPut(body?: UpdateReferenciaMaterialDto, observe?: 'body', reportProgress?: boolean): Observable<ReferenciaMaterialDto>;
    public apiV2ReferenciaMaterialesPut(body?: UpdateReferenciaMaterialDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ReferenciaMaterialDto>>;
    public apiV2ReferenciaMaterialesPut(body?: UpdateReferenciaMaterialDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ReferenciaMaterialDto>>;
    public apiV2ReferenciaMaterialesPut(body?: UpdateReferenciaMaterialDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<ReferenciaMaterialDto>('put',`${this.basePath}/api/v2/referenciaMateriales`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param Q 
     * @param sort 
     * @param page 
     * @param pageSize 
     * @param filters 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV2ReferenciaMaterialesSubFamiliaGet(Q?: string, sort?: string, page?: number, pageSize?: number, filters?: { [key: string]: string; }, observe?: 'body', reportProgress?: boolean): Observable<SubFamiliaReferenciaMaterialDtoPaginatedResult>;
    public apiV2ReferenciaMaterialesSubFamiliaGet(Q?: string, sort?: string, page?: number, pageSize?: number, filters?: { [key: string]: string; }, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SubFamiliaReferenciaMaterialDtoPaginatedResult>>;
    public apiV2ReferenciaMaterialesSubFamiliaGet(Q?: string, sort?: string, page?: number, pageSize?: number, filters?: { [key: string]: string; }, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SubFamiliaReferenciaMaterialDtoPaginatedResult>>;
    public apiV2ReferenciaMaterialesSubFamiliaGet(Q?: string, sort?: string, page?: number, pageSize?: number, filters?: { [key: string]: string; }, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {






        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (Q !== undefined && Q !== null) {
            queryParameters = queryParameters.set('Q', <any>Q);
        }
        if (sort !== undefined && sort !== null) {
            queryParameters = queryParameters.set('Sort', <any>sort);
        }
        if (page !== undefined && page !== null) {
            queryParameters = queryParameters.set('Page', <any>page);
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters = queryParameters.set('PageSize', <any>pageSize);
        }
        if (filters !== undefined && filters !== null) {
            Object.keys(filters).forEach((key) => {queryParameters = queryParameters.set(key, filters[key]);});
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SubFamiliaReferenciaMaterialDtoPaginatedResult>('get',`${this.basePath}/api/v2/referenciaMateriales/subFamilia`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV2ReferenciaMaterialesSubFamiliaIdDelete(id: number, observe?: 'body', reportProgress?: boolean): Observable<SubFamiliaReferenciaMaterialDto>;
    public apiV2ReferenciaMaterialesSubFamiliaIdDelete(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SubFamiliaReferenciaMaterialDto>>;
    public apiV2ReferenciaMaterialesSubFamiliaIdDelete(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SubFamiliaReferenciaMaterialDto>>;
    public apiV2ReferenciaMaterialesSubFamiliaIdDelete(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiV2ReferenciaMaterialesSubFamiliaIdDelete.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SubFamiliaReferenciaMaterialDto>('delete',`${this.basePath}/api/v2/referenciaMateriales/subFamilia/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV2ReferenciaMaterialesSubFamiliaIdGet(id: number, observe?: 'body', reportProgress?: boolean): Observable<SubFamiliaReferenciaMaterialDto>;
    public apiV2ReferenciaMaterialesSubFamiliaIdGet(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SubFamiliaReferenciaMaterialDto>>;
    public apiV2ReferenciaMaterialesSubFamiliaIdGet(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SubFamiliaReferenciaMaterialDto>>;
    public apiV2ReferenciaMaterialesSubFamiliaIdGet(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiV2ReferenciaMaterialesSubFamiliaIdGet.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SubFamiliaReferenciaMaterialDto>('get',`${this.basePath}/api/v2/referenciaMateriales/subFamilia/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV2ReferenciaMaterialesSubFamiliaPost(body?: CreateSubFamiliaReferenciaMaterialDto, observe?: 'body', reportProgress?: boolean): Observable<SubFamiliaReferenciaMaterialDto>;
    public apiV2ReferenciaMaterialesSubFamiliaPost(body?: CreateSubFamiliaReferenciaMaterialDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SubFamiliaReferenciaMaterialDto>>;
    public apiV2ReferenciaMaterialesSubFamiliaPost(body?: CreateSubFamiliaReferenciaMaterialDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SubFamiliaReferenciaMaterialDto>>;
    public apiV2ReferenciaMaterialesSubFamiliaPost(body?: CreateSubFamiliaReferenciaMaterialDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<SubFamiliaReferenciaMaterialDto>('post',`${this.basePath}/api/v2/referenciaMateriales/subFamilia`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV2ReferenciaMaterialesSubFamiliaPut(body?: UpdateSubFamiliaReferenciaMaterialDto, observe?: 'body', reportProgress?: boolean): Observable<SubFamiliaReferenciaMaterialDto>;
    public apiV2ReferenciaMaterialesSubFamiliaPut(body?: UpdateSubFamiliaReferenciaMaterialDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SubFamiliaReferenciaMaterialDto>>;
    public apiV2ReferenciaMaterialesSubFamiliaPut(body?: UpdateSubFamiliaReferenciaMaterialDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SubFamiliaReferenciaMaterialDto>>;
    public apiV2ReferenciaMaterialesSubFamiliaPut(body?: UpdateSubFamiliaReferenciaMaterialDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<SubFamiliaReferenciaMaterialDto>('put',`${this.basePath}/api/v2/referenciaMateriales/subFamilia`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
