/**
 * Valoriza Park API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { CreateUnidadesMedidaDto } from '../model/createUnidadesMedidaDto';
import { CreateUnidadesMedidaLangDto } from '../model/createUnidadesMedidaLangDto';
import { ProblemDetails } from '../model/problemDetails';
import { UnidadesMedidaDto } from '../model/unidadesMedidaDto';
import { UnidadesMedidaDtoPaginatedResult } from '../model/unidadesMedidaDtoPaginatedResult';
import { UnidadesMedidaLangDto } from '../model/unidadesMedidaLangDto';
import { UnidadesMedidaLangDtoPaginatedResult } from '../model/unidadesMedidaLangDtoPaginatedResult';
import { UpdateUnidadesMedidaDto } from '../model/updateUnidadesMedidaDto';
import { UpdateUnidadesMedidaLangDto } from '../model/updateUnidadesMedidaLangDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class UnidadesDeMedidaService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param Q 
     * @param sort 
     * @param page 
     * @param pageSize 
     * @param filters 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV2UnidadesMedidaGet(Q?: string, sort?: string, page?: number, pageSize?: number, filters?: { [key: string]: string; }, observe?: 'body', reportProgress?: boolean): Observable<UnidadesMedidaDtoPaginatedResult>;
    public apiV2UnidadesMedidaGet(Q?: string, sort?: string, page?: number, pageSize?: number, filters?: { [key: string]: string; }, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UnidadesMedidaDtoPaginatedResult>>;
    public apiV2UnidadesMedidaGet(Q?: string, sort?: string, page?: number, pageSize?: number, filters?: { [key: string]: string; }, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UnidadesMedidaDtoPaginatedResult>>;
    public apiV2UnidadesMedidaGet(Q?: string, sort?: string, page?: number, pageSize?: number, filters?: { [key: string]: string; }, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {






        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (Q !== undefined && Q !== null) {
            queryParameters = queryParameters.set('Q', <any>Q);
        }
        if (sort !== undefined && sort !== null) {
            queryParameters = queryParameters.set('Sort', <any>sort);
        }
        if (page !== undefined && page !== null) {
            queryParameters = queryParameters.set('Page', <any>page);
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters = queryParameters.set('PageSize', <any>pageSize);
        }
        if (filters !== undefined && filters !== null) {
            Object.keys(filters).forEach((key) => {queryParameters = queryParameters.set(key, filters[key]);});
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<UnidadesMedidaDtoPaginatedResult>('get',`${this.basePath}/api/v2/unidadesMedida`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV2UnidadesMedidaIdDelete(id: number, observe?: 'body', reportProgress?: boolean): Observable<UnidadesMedidaDto>;
    public apiV2UnidadesMedidaIdDelete(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UnidadesMedidaDto>>;
    public apiV2UnidadesMedidaIdDelete(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UnidadesMedidaDto>>;
    public apiV2UnidadesMedidaIdDelete(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiV2UnidadesMedidaIdDelete.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<UnidadesMedidaDto>('delete',`${this.basePath}/api/v2/unidadesMedida/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV2UnidadesMedidaIdGet(id: number, observe?: 'body', reportProgress?: boolean): Observable<UnidadesMedidaDto>;
    public apiV2UnidadesMedidaIdGet(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UnidadesMedidaDto>>;
    public apiV2UnidadesMedidaIdGet(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UnidadesMedidaDto>>;
    public apiV2UnidadesMedidaIdGet(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiV2UnidadesMedidaIdGet.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<UnidadesMedidaDto>('get',`${this.basePath}/api/v2/unidadesMedida/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param Q 
     * @param sort 
     * @param page 
     * @param pageSize 
     * @param filters 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV2UnidadesMedidaLangGet(Q?: string, sort?: string, page?: number, pageSize?: number, filters?: { [key: string]: string; }, observe?: 'body', reportProgress?: boolean): Observable<UnidadesMedidaLangDtoPaginatedResult>;
    public apiV2UnidadesMedidaLangGet(Q?: string, sort?: string, page?: number, pageSize?: number, filters?: { [key: string]: string; }, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UnidadesMedidaLangDtoPaginatedResult>>;
    public apiV2UnidadesMedidaLangGet(Q?: string, sort?: string, page?: number, pageSize?: number, filters?: { [key: string]: string; }, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UnidadesMedidaLangDtoPaginatedResult>>;
    public apiV2UnidadesMedidaLangGet(Q?: string, sort?: string, page?: number, pageSize?: number, filters?: { [key: string]: string; }, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {






        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (Q !== undefined && Q !== null) {
            queryParameters = queryParameters.set('Q', <any>Q);
        }
        if (sort !== undefined && sort !== null) {
            queryParameters = queryParameters.set('Sort', <any>sort);
        }
        if (page !== undefined && page !== null) {
            queryParameters = queryParameters.set('Page', <any>page);
        }
        if (pageSize !== undefined && pageSize !== null) {
            queryParameters = queryParameters.set('PageSize', <any>pageSize);
        }
        if (filters !== undefined && filters !== null) {
            Object.keys(filters).forEach((key) => {queryParameters = queryParameters.set(key, filters[key]);});
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<UnidadesMedidaLangDtoPaginatedResult>('get',`${this.basePath}/api/v2/unidadesMedida/lang`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param idLang 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV2UnidadesMedidaLangIdDelete(id: number, idLang: number, observe?: 'body', reportProgress?: boolean): Observable<UnidadesMedidaLangDto>;
    public apiV2UnidadesMedidaLangIdDelete(id: number, idLang: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UnidadesMedidaLangDto>>;
    public apiV2UnidadesMedidaLangIdDelete(id: number, idLang: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UnidadesMedidaLangDto>>;
    public apiV2UnidadesMedidaLangIdDelete(id: number, idLang: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiV2UnidadesMedidaLangIdDelete.');
        }

        if (idLang === null || idLang === undefined) {
            throw new Error('Required parameter idLang was null or undefined when calling apiV2UnidadesMedidaLangIdDelete.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (idLang !== undefined && idLang !== null) {
            queryParameters = queryParameters.set('idLang', <any>idLang);
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<UnidadesMedidaLangDto>('delete',`${this.basePath}/api/v2/unidadesMedida/lang/${encodeURIComponent(String(id))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param id 
     * @param idLang 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV2UnidadesMedidaLangIdIdLangGet(id: number, idLang: number, observe?: 'body', reportProgress?: boolean): Observable<UnidadesMedidaLangDto>;
    public apiV2UnidadesMedidaLangIdIdLangGet(id: number, idLang: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UnidadesMedidaLangDto>>;
    public apiV2UnidadesMedidaLangIdIdLangGet(id: number, idLang: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UnidadesMedidaLangDto>>;
    public apiV2UnidadesMedidaLangIdIdLangGet(id: number, idLang: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiV2UnidadesMedidaLangIdIdLangGet.');
        }

        if (idLang === null || idLang === undefined) {
            throw new Error('Required parameter idLang was null or undefined when calling apiV2UnidadesMedidaLangIdIdLangGet.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<UnidadesMedidaLangDto>('get',`${this.basePath}/api/v2/unidadesMedida/lang/${encodeURIComponent(String(id))}/${encodeURIComponent(String(idLang))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV2UnidadesMedidaLangPost(body?: CreateUnidadesMedidaLangDto, observe?: 'body', reportProgress?: boolean): Observable<UnidadesMedidaLangDto>;
    public apiV2UnidadesMedidaLangPost(body?: CreateUnidadesMedidaLangDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UnidadesMedidaLangDto>>;
    public apiV2UnidadesMedidaLangPost(body?: CreateUnidadesMedidaLangDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UnidadesMedidaLangDto>>;
    public apiV2UnidadesMedidaLangPost(body?: CreateUnidadesMedidaLangDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<UnidadesMedidaLangDto>('post',`${this.basePath}/api/v2/unidadesMedida/lang`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV2UnidadesMedidaLangPut(body?: UpdateUnidadesMedidaLangDto, observe?: 'body', reportProgress?: boolean): Observable<UnidadesMedidaLangDto>;
    public apiV2UnidadesMedidaLangPut(body?: UpdateUnidadesMedidaLangDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UnidadesMedidaLangDto>>;
    public apiV2UnidadesMedidaLangPut(body?: UpdateUnidadesMedidaLangDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UnidadesMedidaLangDto>>;
    public apiV2UnidadesMedidaLangPut(body?: UpdateUnidadesMedidaLangDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<UnidadesMedidaLangDto>('put',`${this.basePath}/api/v2/unidadesMedida/lang`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV2UnidadesMedidaPost(body?: CreateUnidadesMedidaDto, observe?: 'body', reportProgress?: boolean): Observable<UnidadesMedidaDto>;
    public apiV2UnidadesMedidaPost(body?: CreateUnidadesMedidaDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UnidadesMedidaDto>>;
    public apiV2UnidadesMedidaPost(body?: CreateUnidadesMedidaDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UnidadesMedidaDto>>;
    public apiV2UnidadesMedidaPost(body?: CreateUnidadesMedidaDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<UnidadesMedidaDto>('post',`${this.basePath}/api/v2/unidadesMedida`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiV2UnidadesMedidaPut(body?: UpdateUnidadesMedidaDto, observe?: 'body', reportProgress?: boolean): Observable<UnidadesMedidaDto>;
    public apiV2UnidadesMedidaPut(body?: UpdateUnidadesMedidaDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UnidadesMedidaDto>>;
    public apiV2UnidadesMedidaPut(body?: UpdateUnidadesMedidaDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UnidadesMedidaDto>>;
    public apiV2UnidadesMedidaPut(body?: UpdateUnidadesMedidaDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<UnidadesMedidaDto>('put',`${this.basePath}/api/v2/unidadesMedida`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
